config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :homes
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
   resources :relationships, only: [:index]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    @books=Book.find(params[:book_id])
    @book_comment = BookComment.new
  end

  def destroy
    @books=Book.find(params[:book_id])
    @book_comment=BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @book_comment.destroy
    @book_comment = BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
  <% books.book_comments.each do |book_comment| %>
    <tr>
    <td><%= image_tag book_comment.user.get_profile_image, size:"100x100" %></td><br>
    <td><%= book_comment.user.name %></td>
    <td><%= book_comment.comment %></td>
    <td><% if book_comment.user == current_user %></td>
    <td><%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete,remote: true,class: "btn btn-sm btn-danger" %></td>
    <% end %>
    </tr>
  <% end %>

  <td>
  <%= form_with model: book_comment,url: book_book_comments_path(books.id),local: false do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
  </td>

app/views/book_comments/create.js.erb
$("#comments-area").html("<%= j(render 'book_comments/comment', books: @books,book_comment: @book_comment) %>")

app/views/book_comments/destroy.js.erb
$("#comments-area").html("<%= j(render 'book_comments/comment', books: @books,book_comment: @book_comment) %>")